// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZt4nT81_CmobzI1Bm8ghjz2m-f9LC-2s',
    appId: '1:1007467050437:web:33fd7b2c4a6b36845587ac',
    messagingSenderId: '1007467050437',
    projectId: 'assignment-3-mad-theory',
    authDomain: 'assignment-3-mad-theory.firebaseapp.com',
    storageBucket: 'assignment-3-mad-theory.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD57NgeVOHLJDjnSfb49AlbNXg2cgDEm_E',
    appId: '1:1007467050437:android:2ed6f1dbc0abb1115587ac',
    messagingSenderId: '1007467050437',
    projectId: 'assignment-3-mad-theory',
    storageBucket: 'assignment-3-mad-theory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACRzGKig_787FoCsB-duoJGlbb6bsYXEc',
    appId: '1:1007467050437:ios:32fcfc4c4a4cad385587ac',
    messagingSenderId: '1007467050437',
    projectId: 'assignment-3-mad-theory',
    storageBucket: 'assignment-3-mad-theory.firebasestorage.app',
    iosBundleId: 'com.addanabdullahsiddiqui.assignment3Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACRzGKig_787FoCsB-duoJGlbb6bsYXEc',
    appId: '1:1007467050437:ios:32fcfc4c4a4cad385587ac',
    messagingSenderId: '1007467050437',
    projectId: 'assignment-3-mad-theory',
    storageBucket: 'assignment-3-mad-theory.firebasestorage.app',
    iosBundleId: 'com.addanabdullahsiddiqui.assignment3Firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZt4nT81_CmobzI1Bm8ghjz2m-f9LC-2s',
    appId: '1:1007467050437:web:af048369c40041445587ac',
    messagingSenderId: '1007467050437',
    projectId: 'assignment-3-mad-theory',
    authDomain: 'assignment-3-mad-theory.firebaseapp.com',
    storageBucket: 'assignment-3-mad-theory.firebasestorage.app',
  );
}
